baseURL = "https://backslashlinux.com/"
languageCode = "en-us"
title = "BackSlash Linux"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = 'light'
  BookToC = false
#   BookLogo = 'logo.png'
  BookMenuBundle = '/menu'
  BookSearch = false
